version: "3.7"

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules/
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - PGHOST=db
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432

  client:
    build: ./client
    depends_on:
      - server
    links:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules/
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  db:
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - ./docker/volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/db-files/
